language: python
python:
  - "3.6"

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-generic-recommended
      - latex-xcolor
      - texlive-fonts-recommended
      - texlive-fonts-extra

before_install:
  - git log -n 4
  - git log -n 1 HEAD^
  - git log -n 4 --no-merges
  - git log -n 1 --no-merges

install:
  - pip install dropbox requests

script:
  - make LATEXOPT=-halt-on-error
  - make clean
  - python .travis-deploy.py
